"""add ingestion run metadata

Revision ID: 58e266e9d5e2
Revises: 7473351d2ca7
Create Date: 2026-09-16 00:55:37.770064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58e266e9d5e2'
down_revision: Union[str, Sequence[str], None] = '7473351d2ca7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_runs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'SUCCESS', 'FAILED', name='ingestion_run_status'), server_default='RUNNING', nullable=False),
    sa.Column('records_fetched', sa.Integer(), server_default='0', nullable=False),
    sa.Column('records_processed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ingestion_runs_source_state_started', 'ingestion_runs', ['source', 'state', 'started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ingestion_runs_source_state_started', table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    # ### end Alembic commands ###
