"""add agmarknet variety and grade

Revision ID: bed375a28175
Revises: 0002_txn_fsm
Create Date: 2026-09-15 22:19:41.369364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bed375a28175'
down_revision: Union[str, Sequence[str], None] = '0002_txn_fsm'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_prices', sa.Column('variety', sa.String(length=100), server_default='Unknown', nullable=False))
    op.add_column('market_prices', sa.Column('grade', sa.String(length=50), server_default='Unknown', nullable=False))
    op.create_unique_constraint(
    'uq_market_price_observation',
    'market_prices',
    [
        'market_id',
        'commodity_id',
        'arrival_date',
        'variety',
        'grade',
        'source',
    ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
    'uq_market_price_observation',
    'market_prices',
    type_='unique',
    )
    op.drop_column('market_prices', 'grade')
    op.drop_column('market_prices', 'variety')
    # ### end Alembic commands ###
