"""initial schema

Revision ID: e2dd6d9a2b45
Revises: 
Create Date: 2026-09-09 14:11:26.747001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e2dd6d9a2b45'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cold_storage_facilities',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('external_facility_code', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('capacity_quintals', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('available_capacity_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('rate_per_quintal_per_day', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('supports_crops', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('data_status', sa.Enum('REAL', 'SYNTHETIC', 'USER_GENERATED', name='cold_storage_data_status'), server_default='SYNTHETIC', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_facility_code')
    )
    op.create_table('commodities',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('local_name', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('fpos',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('verification_status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='fpo_verification_status'), server_default='PENDING', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_number')
    )
    op.create_table('logistics_providers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('external_provider_code', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('vehicle_types', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('rate_per_km_per_quintal', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('base_district', sa.String(length=100), nullable=True),
    sa.Column('avg_rating', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('data_status', sa.Enum('REAL', 'SYNTHETIC', 'USER_GENERATED', name='logistics_provider_data_status'), server_default='SYNTHETIC', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_provider_code')
    )
    op.create_table('markets',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('apmc_name', sa.String(length=200), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), server_default='Maharashtra', nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'district', name='uq_market_name_district')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('FARMER', 'BUYER', 'FPO_ADMIN', 'GOVERNMENT_ADMIN', 'PLATFORM_ADMIN', name='user_role'), nullable=False),
    sa.Column('language', sa.String(length=10), server_default='en', nullable=False),
    sa.Column('location_text', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('buyer_profiles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('external_buyer_code', sa.String(length=20), nullable=True),
    sa.Column('business_name', sa.String(length=200), nullable=False),
    sa.Column('buyer_type', sa.Enum('TRADER', 'PROCESSOR', 'EXPORTER', 'RETAILER', 'INSTITUTION', 'WHOLESALER', name='buyer_type'), nullable=False),
    sa.Column('verification_status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='buyer_verification_status'), server_default='PENDING', nullable=False),
    sa.Column('reliability_score', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('payment_terms', sa.String(length=100), nullable=True),
    sa.Column('target_price_index', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('minimum_grade_accepted', sa.Enum('A', 'B', 'C', name='buyer_min_grade'), nullable=True),
    sa.Column('past_deals_completed', sa.Integer(), server_default='0', nullable=True),
    sa.Column('past_deals_disputed', sa.Integer(), server_default='0', nullable=True),
    sa.Column('registered_since', sa.Date(), nullable=True),
    sa.Column('kyc_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('data_status', sa.Enum('REAL', 'SYNTHETIC', 'USER_GENERATED', name='buyer_data_status'), server_default='SYNTHETIC', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_buyer_code'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('farmer_profiles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('land_size', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('primary_location', sa.String(length=200), nullable=True),
    sa.Column('fpo_id', sa.BigInteger(), nullable=True),
    sa.Column('preferred_language', sa.String(length=10), server_default='en', nullable=False),
    sa.Column('crops', postgresql.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['fpo_id'], ['fpos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('market_prices',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('market_id', sa.BigInteger(), nullable=False),
    sa.Column('commodity_id', sa.BigInteger(), nullable=False),
    sa.Column('arrival_date', sa.Date(), nullable=False),
    sa.Column('min_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('modal_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('arrival_quantity', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('unit', sa.String(length=20), server_default='quintal', nullable=False),
    sa.Column('source', sa.Enum('AGMARKNET', 'DATA_GOV_IN', 'ENAM', 'SYNTHETIC', name='market_price_source'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('min_price >= 0 AND max_price >= min_price AND modal_price >= min_price AND modal_price <= max_price', name='ck_market_price_bounds'),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_market_prices_lookup', 'market_prices', ['commodity_id', 'market_id', 'arrival_date'], unique=False)
    op.create_table('buyer_demands',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('buyer_id', sa.BigInteger(), nullable=False),
    sa.Column('commodity_id', sa.BigInteger(), nullable=False),
    sa.Column('required_quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('minimum_grade', sa.Enum('A', 'B', 'C', name='demand_min_grade'), nullable=True),
    sa.Column('maximum_grade', sa.Enum('A', 'B', 'C', name='demand_max_grade'), nullable=True),
    sa.Column('target_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='OPEN', nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyer_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fpo_members',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('fpo_id', sa.BigInteger(), nullable=False),
    sa.Column('farmer_id', sa.BigInteger(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmer_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fpo_id'], ['fpos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fpo_id', 'farmer_id', name='uq_fpo_member')
    )
    op.create_table('lots',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('farmer_id', sa.BigInteger(), nullable=False),
    sa.Column('fpo_id', sa.BigInteger(), nullable=True),
    sa.Column('commodity_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=20), server_default='quintal', nullable=False),
    sa.Column('grade', sa.Enum('A', 'B', 'C', name='lot_grade'), nullable=False),
    sa.Column('harvest_date', sa.Date(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('expected_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'MATCHED', 'NEGOTIATING', 'SOLD', 'IN_TRANSIT', 'DELIVERED', 'CLOSED', 'CANCELLED', name='lot_status'), server_default='DRAFT', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_lot_quantity_positive'),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmer_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fpo_id'], ['fpos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lot_images',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('lot_id', sa.BigInteger(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('image_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('lot_id', sa.BigInteger(), nullable=False),
    sa.Column('buyer_id', sa.BigInteger(), nullable=False),
    sa.Column('parent_offer_id', sa.BigInteger(), nullable=True),
    sa.Column('offer_price_per_quintal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity_quintals', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_realization_at_offer', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('match_score_at_offer', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COUNTERED', 'ACCEPTED', 'REJECTED', 'EXPIRED', name='offer_status'), server_default='PENDING', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('offer_price_per_quintal >= 0 AND quantity_quintals > 0', name='ck_offer_values_positive'),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyer_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_offer_id'], ['offers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quality_grades',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('lot_id', sa.BigInteger(), nullable=False),
    sa.Column('grade', sa.Enum('A', 'B', 'C', name='quality_grade'), nullable=False),
    sa.Column('quality_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('defect_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('size_category', sa.String(length=50), nullable=True),
    sa.Column('moisture', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('inspection_method', sa.String(length=50), server_default='AI_ESTIMATED', nullable=False),
    sa.Column('verified', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint("inspection_method IN ('AI_ESTIMATED', 'HUMAN_VERIFIED')", name='ck_quality_inspection_method'),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('lot_id', sa.BigInteger(), nullable=False),
    sa.Column('offer_id', sa.BigInteger(), nullable=False),
    sa.Column('farmer_id', sa.BigInteger(), nullable=False),
    sa.Column('buyer_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity_quintals', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('agreed_price_per_quintal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('gross_revenue', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_realization', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('OFFER_ACCEPTED', 'PAYMENT_INITIATED', 'LOGISTICS_ARRANGED', 'IN_TRANSIT', 'DELIVERED', 'PAYMENT_CONFIRMED', 'COMPLETED', 'CANCELLED', name='transaction_status'), server_default='OFFER_ACCEPTED', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyer_profiles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmer_profiles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('offer_id')
    )
    op.create_table('grievances',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ticket_id', sa.String(length=30), nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('filed_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('complaint_type', sa.Enum('payment_not_received', 'quality_mismatch', 'quantity_mismatch', 'buyer_unresponsive', 'logistics_delay', 'other', name='grievance_complaint_type'), nullable=False),
    sa.Column('raw_complaint_type_input', sa.String(length=100), nullable=True),
    sa.Column('matched_known_category', sa.Boolean(), nullable=False),
    sa.Column('complaint_text', sa.Text(), nullable=True),
    sa.Column('days_since_issue', sa.Integer(), server_default='0', nullable=False),
    sa.Column('escalated', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', name='grievance_severity'), nullable=False),
    sa.Column('status', sa.Enum('open_awaiting_response', 'escalated_to_admin_review', 'resolved', 'closed', name='grievance_status'), server_default='open_awaiting_response', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['filed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_id')
    )
    op.create_table('logistics_bookings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), nullable=False),
    sa.Column('provider_id', sa.BigInteger(), nullable=True),
    sa.Column('storage_facility_id', sa.BigInteger(), nullable=True),
    sa.Column('distance_km', sa.Numeric(precision=8, scale=1), nullable=True),
    sa.Column('distance_source', sa.Enum('HAVERSINE_PROXY', 'LIVE_OSM', 'LIVE_OSM_ATTEMPTED_FALLBACK', name='distance_source'), nullable=True),
    sa.Column('transport_cost_inr', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Enum('BOOKED', 'IN_TRANSIT', 'DELIVERED', 'CANCELLED', name='logistics_booking_status'), server_default='BOOKED', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['logistics_providers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['storage_facility_id'], ['cold_storage_facilities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('INITIATED', 'PROCESSING', 'CONFIRMED', 'FAILED', name='payment_status'), server_default='INITIATED', nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expected_payment_date', sa.Date(), nullable=True),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('is_simulated', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('logistics_bookings')
    op.drop_table('grievances')
    op.drop_table('transactions')
    op.drop_table('quality_grades')
    op.drop_table('offers')
    op.drop_table('lot_images')
    op.drop_table('lots')
    op.drop_table('fpo_members')
    op.drop_table('buyer_demands')
    op.drop_index('ix_market_prices_lookup', table_name='market_prices')
    op.drop_table('market_prices')
    op.drop_table('farmer_profiles')
    op.drop_table('buyer_profiles')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('markets')
    op.drop_table('logistics_providers')
    op.drop_table('fpos')
    op.drop_table('commodities')
    op.drop_table('cold_storage_facilities')
    # ### end Alembic commands ###

    # NOTE: alembic autogenerate does not emit DROP TYPE for Postgres ENUMs
    # on downgrade (it only tracks table lifecycle, not the standalone enum
    # objects each Enum column creates). Left as-is, a downgrade-then-upgrade
    # cycle fails on "type already exists" -- caught by
    # tests/test_db_schema.py::test_downgrade_then_upgrade_roundtrip, fixed
    # here by dropping every enum type this migration created.
    for enum_name in [
        "cold_storage_data_status", "fpo_verification_status",
        "logistics_provider_data_status", "user_role", "buyer_type",
        "buyer_verification_status", "buyer_min_grade", "buyer_data_status",
        "market_price_source", "demand_min_grade", "demand_max_grade",
        "lot_grade", "lot_status", "offer_status", "quality_grade",
        "transaction_status", "grievance_complaint_type", "grievance_severity",
        "grievance_status", "distance_source", "logistics_booking_status",
        "payment_status",
    ]:
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
